name: Build and Push Docker Image and Update GitOps

on:
  push:
    branches:
      - main
    tags:
      - "*"  # Triggers workflow when a tag is pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Only need read access to checkout code
      packages: write  # Need write access to push Docker image

    outputs:
      short_sha: ${{ steps.get_sha.outputs.SHORT_SHA }} # Expose SHORT_SHA as a job output

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Using v4 for actions/checkout, generally recommended to use the latest stable version

      - name: Get short commit SHA
        id: get_sha # Assign an ID to this step to access its outputs
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT # Correct way to set step outputs

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Using v3 for docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Using v3 for docker/setup-buildx-action

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Using v5 for docker/build-push-action
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jwt:${{ env.SHORT_SHA }} # env.SHORT_SHA from previous step is fine here

  update-gitops:
    runs-on: ubuntu-latest
    needs: build-and-push # This job depends on the successful completion of the build-and-push job
    permissions:
      contents: write # Crucial: Grant write permission to push changes to the repository

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4 # Using v4 for actions/checkout

      - name: Update image tag in deployment.yaml
        run: |
          # Access the SHA from the previous job's output
          IMAGE_SHA="${{ needs.build-and-push.outputs.short_sha }}"

          # Navigate to your GitOps folder
          cd GitOps

          # Assuming your deployment.yaml has an image tag like "image: your-repo/your-image:old-tag"
          # This 'sed' command will replace the image tag.
          sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/jwt:.*|image: ${{ secrets.DOCKER_USERNAME }}/jwt:$IMAGE_SHA|g" deployment.yaml

          # Commit the changes
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deployment.yaml
          git commit -m "Update jwt image to $IMAGE_SHA"

          # Push the changes back to the repository using the GITHUB_TOKEN
          git push